name: build/docker

on:
  workflow_call:
    inputs:
      publish:
        required: true
        type: boolean

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@49819abfb41bd9b44fb781159c033dba90353a7c
        with:
          swap-size-gb: 12

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: "go.sum"
          check-latest: true

      - name: Run Golangci lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --print-resources-usage

  build:
    name: "build ${{ matrix.Dockerfile }}:${{ matrix.target }}"
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        include:
          - Dockerfile: Dockerfile
            target: "final-static"
            suffix: ""
            latest: "auto"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@49819abfb41bd9b44fb781159c033dba90353a7c
        with:
          swap-size-gb: 12

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: "go.sum"
          check-latest: true

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          labels: |
            io.artifacthub.package.readme-url=https://raw.githubusercontent.com/${{ github.repository }}/${{ github.event.repository.default_branch }}/README.md
          flavor: |
            latest=${{ matrix.latest }}
            suffix=${{ matrix.suffix }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Packages Container registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: ${{ inputs.publish && 'Build and push' || 'Build' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./${{ matrix.Dockerfile }}
          target: ${{ matrix.target }}
          platforms: linux/amd64,linux/arm64
          push: ${{ inputs.publish }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
